# Model Training using DistilBERT

In this notebook, we fine-tune the pretrained DistilBERT model on the BANKING77 dataset.

We use Transfer Learning instead of training a transformer from scratch because:

- Faster
- Better Accuracy
- Requires Less Data
- Lower Computational Cost

## Importing Libraries

In [2]:
import pandas as pd
import numpy as np
import torch
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    TrainingArguments,
    Trainer
)
from sklearn.metrics import accuracy_score

In [3]:
# Checking Torch Version
print(torch.__version__)

2.13.0+cpu

In [4]:
#Gpu Check
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using Device :", device)

Using Device : cpu

## Loading Processed Data

In [5]:
train_df = pd.read_csv("../Data/train_processed.csv")

test_df = pd.read_csv("../Data/test_processed.csv")

In [6]:
train_df

,text,category,query_length,label
0,I am still waiting on my card?,card_arrival,30,12
1,What can I do if my card still hasn't arrived ...,card_arrival,60,12
2,I have been waiting over a week. Is the card s...,card_arrival,58,12
3,Can I track my card while it is in the process...,card_arrival,59,12
4,"How do I know if I will get my card, or if it ...",card_arrival,54,12
...,...,...,...,...
9998,You provide support in what countries?,country_support,38,25
9999,What countries are you supporting?,country_support,34,25
10000,What countries are getting support?,country_support,35,25
10001,Are cards available in the EU?,country_support,30,25
10002,Which countries are represented?,country_support,32,25

In [7]:
test_df

,text,category,query_length,label
0,How do I locate my card?,card_arrival,24,12
1,"I still have not received my new card, I order...",card_arrival,65,12
2,I ordered a card but it has not arrived. Help ...,card_arrival,53,12
3,Is there a way to know when my card will arrive?,card_arrival,48,12
4,My card has not arrived yet.,card_arrival,28,12
...,...,...,...,...
3075,"If i'm not in the UK, can I still get a card?",country_support,45,25
3076,How many countries do you support?,country_support,34,25
3077,What countries do you do business in?,country_support,37,25
3078,What are the countries you operate in.,country_support,38,25
3079,Can the card be mailed and used in Europe?,country_support,42,25

In [8]:
# Load Tokenizer
tokenizer = DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
)

In [9]:
# Convert Pandas -> HuggingFace Dataset
from datasets import Dataset
train_dataset = Dataset.from_pandas(train_df)
train_dataset

Dataset({
    features: ['text', 'category', 'query_length', 'label'],
    num_rows: 10003
})

In [10]:
test_dataset = Dataset.from_pandas(test_df)
test_dataset

Dataset({
    features: ['text', 'category', 'query_length', 'label'],
    num_rows: 3080
})

In [11]:
# TOKENIZATION

def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation = True,
        padding = "max_length",
        max_length = 64
    )

In [12]:
# Apply Tokenizer
train_dataset = train_dataset.map(
    tokenize,
    batched = True
)

test_dataset = test_dataset.map(
    tokenize,
    batched = True
)

Map:   0%|          | 0/10003 [00:00<?, ? examples/s]

Map:   0%|          | 0/3080 [00:00<?, ? examples/s]

In [13]:
# Removing Extra Cols
train_dataset = train_dataset.remove_columns(
    ["text","category","query_length"]
)
test_dataset = test_dataset.remove_columns(
    ["text","category","query_length"]
)

In [14]:
#Renaming label col
train_dataset = train_dataset.rename_column(
    "label",
    "labels"
)

test_dataset = test_dataset.rename_column(
    "label",
    "labels"
)

In [15]:
# In Pytorch format
train_dataset.set_format("torch")
test_dataset.set_format("torch")

In [16]:
train_dataset

Dataset({
    features: ['labels', 'input_ids', 'attention_mask'],
    num_rows: 10003
})

In [17]:
test_dataset

Dataset({
    features: ['labels', 'input_ids', 'attention_mask'],
    num_rows: 3080
})

In [18]:
# Load Model : DistilBERT

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels = 77
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [19]:
model.to(device)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=77, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [20]:
pip install transformers[torch]

Requirement already satisfied: transformers[torch] in c:\users\admin\anaconda3\lib\site-packages (5.14.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (1.24.0)
Requirement already satisfied: numpy>=1.17 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from transformers[torch]) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (2026.7.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (0.17.4)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: torch>=2.4 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (2.13.0)
Requirement already satisfied: accelerate>=1.1.0 in c:\users\admin\anaconda3\lib\site-packages (from transformers[torch]) (1.14.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\admin\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\admin\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\admin\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\admin\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\admin\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python313\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: anyio in c:\users\admin\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.10.0)
Requirement already satisfied: certifi in c:\users\admin\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\admin\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\admin\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: psutil in c:\users\admin\appdata\roaming\python\python313\site-packages (from accelerate>=1.1.0->transformers[torch]) (7.2.1)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\admin\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\admin\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\admin\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.5)
Requirement already satisfied: jinja2 in c:\users\admin\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\admin\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\admin\anaconda3\lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\admin\anaconda3\lib\site-packages (from typer->transformers[torch]) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers[torch]) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from rich>=10.11.0->typer->transformers[torch]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers[torch]) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [21]:
# Training Args

training_args = TrainingArguments(
    output_dir = "models/saved_model",
    eval_strategy = "epoch", 
    save_strategy = "epoch",
    learning_rate = 2e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 3,
    weight_decay = 0.01,
    logging_steps = 100,
    load_best_model_at_end = True,
    metric_for_best_model = "accuracy"
)

In [22]:
# Evaluation Function

def compute_metrics(pred):
    prediction = np.argmax(
        pred.predictions,
        axis = 1
    )

    accuracy = accuracy_score(
        pred.label_ids,
        prediction
    )

    return {
        "accuracy" : accuracy
    }

In [23]:
# Trainer

trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = test_dataset,
    compute_metrics = compute_metrics
)
trainer.train()

C:\Users\Admin\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Admin\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Admin\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1878, training_loss=1.825251972332549, metrics={'train_runtime': 13853.3592, 'train_samples_per_second': 2.166, 'train_steps_per_second': 0.136, 'total_flos': 497566386108288.0, 'train_loss': 1.825251972332549, 'epoch': 3.0})

In [24]:
trainer.evaluate()

C:\Users\Admin\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.8497278094291687, 'eval_accuracy': 0.8594155844155844}

In [25]:
trainer.save_model("models/saved_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [26]:
tokenizer.save_pretrained(
    "models/saved_model"
)

('models/saved_model\\tokenizer_config.json',
 'models/saved_model\\tokenizer.json')

In [27]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

model = AutoModelForSequenceClassification.from_pretrained("models/saved_model")
tokenizer = AutoTokenizer.from_pretrained("models/saved_model")

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [28]:
history = trainer.state.log_history
history

[{'loss': 4.254554443359375,
  'grad_norm': 3.755857229232788,
  'learning_rate': 1.894568690095847e-05,
  'epoch': 0.1597444089456869,
  'step': 100},
 {'loss': 3.837513427734375,
  'grad_norm': 5.2450270652771,
  'learning_rate': 1.788072417465389e-05,
  'epoch': 0.3194888178913738,
  'step': 200},
 {'loss': 3.35986328125,
  'grad_norm': 5.9568634033203125,
  'learning_rate': 1.6815761448349307e-05,
  'epoch': 0.4792332268370607,
  'step': 300},
 {'loss': 2.946711120605469,
  'grad_norm': 5.645184516906738,
  'learning_rate': 1.5750798722044728e-05,
  'epoch': 0.6389776357827476,
  'step': 400},
 {'loss': 2.553294830322266,
  'grad_norm': 6.78502082824707,
  'learning_rate': 1.468583599574015e-05,
  'epoch': 0.7987220447284346,
  'step': 500},
 {'loss': 2.2656430053710936,
  'grad_norm': 6.254422187805176,
  'learning_rate': 1.3620873269435571e-05,
  'epoch': 0.9584664536741214,
  'step': 600},
 {'eval_loss': 1.9922140836715698,
  'eval_accuracy': 0.7155844155844155,
  'eval_runtime': 358.6864,
  'eval_samples_per_second': 8.587,
  'eval_steps_per_second': 0.538,
  'epoch': 1.0,
  'step': 626},
 {'loss': 1.9558641052246093,
  'grad_norm': 5.9329023361206055,
  'learning_rate': 1.2555910543130992e-05,
  'epoch': 1.1182108626198084,
  'step': 700},
 {'loss': 1.7067161560058595,
  'grad_norm': 6.655721664428711,
  'learning_rate': 1.1490947816826413e-05,
  'epoch': 1.2779552715654952,
  'step': 800},
 {'loss': 1.5265234375,
  'grad_norm': 5.912841320037842,
  'learning_rate': 1.0425985090521832e-05,
  'epoch': 1.4376996805111821,
  'step': 900},
 {'loss': 1.3845884704589844,
  'grad_norm': 6.60177755355835,
  'learning_rate': 9.361022364217253e-06,
  'epoch': 1.5974440894568689,
  'step': 1000},
 {'loss': 1.2418878173828125,
  'grad_norm': 8.233780860900879,
  'learning_rate': 8.296059637912674e-06,
  'epoch': 1.7571884984025559,
  'step': 1100},
 {'loss': 1.1443334197998047,
  'grad_norm': 5.984634876251221,
  'learning_rate': 7.231096911608094e-06,
  'epoch': 1.9169329073482428,
  'step': 1200},
 {'eval_loss': 1.058516502380371,
  'eval_accuracy': 0.8357142857142857,
  'eval_runtime': 380.006,
  'eval_samples_per_second': 8.105,
  'eval_steps_per_second': 0.508,
  'epoch': 2.0,
  'step': 1252},
 {'loss': 1.0518428039550782,
  'grad_norm': 4.203935146331787,
  'learning_rate': 6.166134185303515e-06,
  'epoch': 2.07667731629393,
  'step': 1300},
 {'loss': 0.9692620849609375,
  'grad_norm': 8.493940353393555,
  'learning_rate': 5.101171458998936e-06,
  'epoch': 2.236421725239617,
  'step': 1400},
 {'loss': 0.9085667419433594,
  'grad_norm': 6.571506500244141,
  'learning_rate': 4.0362087326943564e-06,
  'epoch': 2.3961661341853033,
  'step': 1500},
 {'loss': 0.8741506958007812,
  'grad_norm': 5.8790693283081055,
  'learning_rate': 2.9712460063897764e-06,
  'epoch': 2.5559105431309903,
  'step': 1600},
 {'loss': 0.8399106597900391,
  'grad_norm': 7.627804756164551,
  'learning_rate': 1.906283280085197e-06,
  'epoch': 2.7156549520766773,
  'step': 1700},
 {'loss': 0.8207975769042969,
  'grad_norm': 6.83575439453125,
  'learning_rate': 8.413205537806178e-07,
  'epoch': 2.8753993610223643,
  'step': 1800},
 {'eval_loss': 0.8497278094291687,
  'eval_accuracy': 0.8594155844155844,
  'eval_runtime': 392.3167,
  'eval_samples_per_second': 7.851,
  'eval_steps_per_second': 0.492,
  'epoch': 3.0,
  'step': 1878},
 {'train_runtime': 13853.3592,
  'train_samples_per_second': 2.166,
  'train_steps_per_second': 0.136,
  'total_flos': 497566386108288.0,
  'train_loss': 1.825251972332549,
  'epoch': 3.0,
  'step': 1878},
 {'eval_loss': 0.8497278094291687,
  'eval_accuracy': 0.8594155844155844,
  'eval_runtime': 390.9054,
  'eval_samples_per_second': 7.879,
  'eval_steps_per_second': 0.494,
  'epoch': 3.0,
  'step': 1878}]